---
- name: 'Prepare'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Ensure Administrator is enabled'
      win_user:
        name: 'Administrator'
        password: 'Asdf!234'
        state: present
        groups:
          - Administrators
